=== RaananW/BJS-CU/myBabylonJS/babylon.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xi="http://www.w3.org/2001/XInclude">

  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude" />
  
  <!-- <files> -->
  <xsd:element name="files">
    <xsd:complexType>
      <xsd:sequence minOccurs="0">
        <xsd:element ref="xi:include" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="script" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="UniqueSrc">
      <xsd:selector xpath="./script" />
      <xsd:field xpath="@src" />
    </xsd:unique>
  </xsd:element>
  <!-- </files> -->

  <!-- END ROOT -->

  <!-- FIRST LEVEL -->

  <!-- <script> -->
  <xsd:element name="script">
    <xsd:complexType>
      <xsd:sequence minOccurs="0">
       <xsd:element ref="dependsOn" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" use="optional" />
      <xsd:attribute name="src" type="xsd:token" use="required" />
    </xsd:complexType>
    <xsd:key name="refScript">
      <xsd:selector xpath="./script" />
      <xsd:field xpath="@id"/>
    </xsd:key>
  </xsd:element>
  <!-- </script> -->

  <!-- END FIRST LEVEL -->

  <!-- SECOND LEVEL -->

  <!-- <dependsOn> -->
  <xsd:element name="dependsOn">
    <xsd:complexType>
      <xsd:attribute name="scriptref" type="xsd:IDREF" use="required" />
    </xsd:complexType>
    <xsd:keyref name="keyrefScript" refer="refScript">
      <xsd:selector xpath="./script/dependsOn" />
      <xsd:field xpath="@scriptref" />
    </xsd:keyref>
  </xsd:element>
  <!-- </dependsOn> -->

  <!-- END SECOND LEVEL -->
  
</xsd:schema>

=== RaananW/BJS-CU/myBabylonJS/babylon.xml
<?xml version="1.0" encoding="utf-8" ?>
<files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="babylon.xsd">
  <script src="Babylon/Physics/babylon.physicsEngine.js"></script>
  <script src="Babylon/Tools/babylon.filesInput.js"></script>
  <script src="Babylon/Collisions/babylon.pickingInfo.js"></script>
  <script src="Babylon/LensFlare/babylon.lensFlareSystem.js"></script>
  <script src="Babylon/LensFlare/babylon.lensFlare.js"></script>
  <script src="Babylon/PostProcess/babylon.fxaaPostProcess.js"></script>
  <script src="Babylon/PostProcess/babylon.convolutionPostProcess.js"></script>
  <script src="Babylon/PostProcess/babylon.blackAndWhitePostProcess.js"></script>
  <script src="Babylon/PostProcess/babylon.refractionPostProcess.js"></script>
  <script src="Babylon/PostProcess/babylon.blurPostProcess.js"></script>
  <script src="Babylon/PostProcess/babylon.passPostProcess.js"></script>
  <script src="Babylon/PostProcess/babylon.postProcessManager.js"></script>
  <script src="Babylon/PostProcess/babylon.postProcess.js"></script>
  <script src="Babylon/Bones/babylon.skeleton.js"></script>
  <script src="Babylon/Bones/babylon.bone.js"></script>
  <script src="Babylon/Culling/Octrees/babylon.octreeBlock.js"></script>
  <script src="Babylon/Culling/Octrees/babylon.octree.js"></script>
  <script src="Babylon/Animations/babylon.animatable.js"></script>
  <script src="Babylon/Animations/babylon.animation.js"></script>
  <script src="Babylon/Particles/babylon.particleSystem.js"></script>
  <script src="Babylon/Particles/babylon.particle.js"></script>
  <script src="Babylon/Layer/babylon.layer.js"></script>
  <script src="Babylon/Sprites/babylon.sprite.js"></script>
  <script src="Babylon/Sprites/babylon.spriteManager.js"></script>
  <script src="Babylon/Tools/babylon.sceneLoader.js"></script>
  <script src="Babylon/Tools/babylon.database.js"></script>
  <script src="Babylon/Materials/babylon.multiMaterial.js"></script>
  <script src="Babylon/Materials/babylon.standardMaterial.js"></script>
  <script src="Babylon/Materials/babylon.material.js"></script>
  <script src="Babylon/Materials/babylon.effect.js"></script>
  <script src="Babylon/Materials/textures/babylon.videoTexture.js"></script>
  <script src="Babylon/Materials/textures/babylon.dynamicTexture.js"></script>
  <script src="Babylon/Materials/textures/babylon.mirrorTexture.js"></script>
  <script src="Babylon/Materials/textures/babylon.renderTargetTexture.js"></script>
  <script src="Babylon/Materials/textures/babylon.cubeTexture.js"></script>
  <script src="Babylon/Materials/textures/babylon.texture.js"></script>
  <script src="Babylon/Rendering/babylon.renderingManager.js"></script>
  <script src="Babylon/Rendering/babylon.renderingGroup.js"></script>
  <script src="Babylon/Materials/textures/babylon.baseTexture.js"></script>
  <script src="Babylon/Mesh/babylon.subMesh.js"></script>
  <script src="Babylon/Mesh/babylon.mesh.js"></script>
  <script src="Babylon/Mesh/babylon.vertexBuffer.js"></script>
  <script src="Babylon/babylon.scene.js"></script>
  <script src="Babylon/Cameras/babylon.arcRotateCamera.js"></script>
  <script src="Babylon/Cameras/babylon.deviceOrientationCamera.js"></script>
  <script src="Babylon/Cameras/babylon.touchCamera.js"></script>
  <script src="Babylon/Cameras/babylon.freeCamera.js"></script>
  <script src="Babylon/Cameras/babylon.camera.js"></script>
  <script src="Babylon/Collisions/babylon.collider.js"></script>
  <script src="Babylon/Lights/babylon.hemisphericLight.js"></script>
  <script src="Babylon/Lights//Shadows/babylon.shadowGenerator.js"></script>
  <script src="Babylon/Lights/babylon.directionalLight.js"></script>
  <script src="Babylon/Lights/babylon.spotlight.js"></script>
  <script src="Babylon/Lights/babylon.pointLight.js"></script>
  <script src="Babylon/Lights/babylon.light.js"></script>
  <script src="Babylon/Culling/babylon.boundingInfo.js"></script>
  <script src="Babylon/Culling/babylon.boundingBox.js"></script>
  <script src="Babylon/Culling/babylon.boundingSphere.js"></script>
  <script src="Babylon/babylon.engine.js"></script>
  <script src="Babylon/Tools/babylon.tools.js"></script>
  <script src="Babylon/Tools/babylon.math.js"></script>
  <script src="Babylon/babylon.node.js"></script>
</files>
